### ISSUE TITLE
What is the frontend url to access app?

### ISSUE THREAD

**Issue by kapil-infobeans** [Bikranshu/lumen-react#3]
What is the frontend url to access app? I mean port number after localhost:?

http://localhost:8000/ gives 500 error with following log:

```
[Tue Mar 31 20:41:37 2020] PHP Warning:  Unknown: failed to open stream: No such file or directory in Unknown on line 0
[Tue Mar 31 20:41:37 2020] PHP Fatal error:  Unknown: Failed opening required '/public/' (include_path='.:/usr/share/php') in Unknown on line 0
```

**Comment by Bikranshu** [comment]
Have you follow this step: cp .env.example .env

**Comment by kapil-infobeans** [comment]
Yes, I have followed all listed commands. You can delete this issue, I will follow up from my personal email to understand how it works.
